# hyprlock configuration
# Layar kunci Hyprland.

general {
    hide_cursor = true
}

background {
    monitor =
    path = /usr/share/hypr/wall0.png
    blur_passes = 3
    blur_size = 8
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = sans-serif
    color = rgba(cdd6f4ee)
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(89b4faee)
    inner_color = rgba(1e1e2ecc)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4">Password...</span>
    position = 0, -20
    halign = center
    valign = center
}
